name: apparche
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  flutter_webview_plugin: ^0.3.11
  youtube_player_flutter: ^8.0.0
  flutter_local_notifications: ^5.0.0+1
  firebase_messaging: ^9.1.1
  http: ^0.13.1
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.6
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.1
  state_persistence: ^0.1.0
  json_serializable: ^4.1.1
  flutter_statusbar_manager: ^2.0.0
  flutter_cached_pdfview: ^0.4.0-nullsafety
  google_maps_flutter: ^2.0.3
  grouped_list: ^4.0.0
  rxdart: ^0.26.0
  path_provider: ^2.0.1
  android_alarm_manager: ^2.0.0
  shared_preferences: ^2.0.5
  flutter_settings_screens: ^0.2.2+1
  flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path: "asset/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/img/splashscreen.jpg
    - asset/img/bg.jpg
    - asset/img/bg2.jpg
    - asset/img/mardi.jpg
    - asset/img/jeudi.jpg
    - asset/img/find-us.jpg
    - asset/img/church-vision.jpg
    - asset/img/pastor.jpg
    - asset/img/Actua.png
    - asset/img/med.png
    - asset/img/video.png
    - asset/img/par.png
    - asset/img/par.png
    - asset/img/hhh.png
    - asset/img/logo.png
    - asset/img/pasteur.png
    - asset/img/dimanche.jpg
    - asset/img/Facebook.png
    - asset/img/background.jpg
    - asset/img/undraw_online_articles_79ff.png
    - asset/img/loading.png
    - asset/pdf/Historique.pdf
    - asset/pdf/AFFERMISSEMENTS.pdf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
